### ISSUE TITLE
the result not accurate

### ISSUE THREAD

**Issue by Carla-33** [ramisa2108/NS3-AODV-Optimized-Route-Discovery-Using-K-Means-Clustering#7]
I have some comment why when run the code several time it change the result ? I mean the measure of throughput and etc, its not static.
How you can modify this issue? 
or tell us the reason for that.

**Comment by Carla-33** [comment]
also, I have another question:
 If I want to stop the program simulation from total time simulation to the number of packets sent. You used this sentence
      Simulator::Stop(Seconds(m_totalTime));
to stop in total time simulation.
I NEED HELP, TELL me what I should do to stop the simulation using the number packet transmitted rather than total time simulation.
Give me a hint.
Please Ramisa answer me.
I need your HELP

**Comment by ramisa2108** [comment]
About your first problem - the results are not likely to remain static since there are several places in the code where randomization is being introduced. For example, the initial cluster heads are picked randomly, and the mobility of the nodes is also random. So, exact reproduction of the results is not possible unless you fix a seed for random number generation and somehow manage to have the pattern of mobility fixed for the nodes (I don't know how this can be done). 

About the second problem, I'm not sure how you can do that. Have you tried using if conditions for it? 
I would suggest you ask questions like the second one in the Google groups for ns3-users. You are more likely to find your answers there. I am not exactly an expert in ns3 and currently, I'm not working with ns3. 
Please only report issues relevant to this particular repository (like your first question) here.
